" --- Florian Wallners vimrc ---
" Core settings are managed in .vimcommon
source ~/.config/vim/vimcommon

" XDG Path for State (Undo, Info)
let g:vim_state_home = $HOME . '/.local/state/vim'
let g:vim_data_home = $HOME . '/.local/share/vim'

if !isdirectory(g:vim_state_home . '/undo')
    call mkdir(g:vim_state_home . '/undo', "p")
endif

" Set storage locations
let &undodir = g:vim_state_home . '/undo'
let &viminfofile = g:vim_state_home . '/viminfo'

" Tell Vim where to find your own packages (in addition to system ones)
set packpath^=~/.local/share/vim

" --- Plugin Configuration (Set variables for system plugins) ---
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'catppuccin_mocha' " From catppuccin/vim plugin
let g:airline_left_sep = '' 
let g:airline_right_sep = ''

" Lumen settings
let g:lumen_light_colorscheme = 'catppuccin_latte'
let g:lumen_dark_colorscheme = 'catppuccin_frappe'

" --- Plugin Management with minpac (ONLY for non-system plugins) ---
function! PackInit() abort
    let l:minpac_path = g:vim_data_home . '/pack/minpac/opt/minpac'
    if empty(glob(l:minpac_path))
        execute 'silent !git clone --quiet https://github.com/k-takata/minpac.git ' . l:minpac_path
    endif

    packadd minpac
    call minpac#init({'dir': g:vim_data_home})
    call minpac#add('k-takata/minpac', {'type': 'opt'})

    " Supplemental plugins (not in /usr/share/vim/vimfiles)
    call minpac#add('tpope/vim-sensible')
    call minpac#add('tpope/vim-sleuth')
    call minpac#add('spf13/vim-autoclose')
    call minpac#add('andymass/vim-matchup')
    call minpac#add('tpope/vim-repeat')
    call minpac#add('tpope/vim-surround')
    call minpac#add('tpope/vim-speeddating')
    call minpac#add('catppuccin/vim', {'as': 'catppuccin'})
    call minpac#add('vimpostor/vim-lumen')
    
    if executable('ctags')
        call minpac#add('majutsushi/tagbar')
    endif
endfunction

command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus packadd minpac | call minpac#status()

" --- Other Settings ---
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_CompileRule_pdf='latexmk -pdf $*'

let gitroot = substitute(system('git rev-parse --show-toplevel'), '[\n\r]', '', 'g')
if gitroot != '' | let &tags = &tags . ',' . gitroot . '/.git/tags' | endif

nnoremap <leader>p :GFiles<CR>
